# Generated by Django 3.1.4 on 2020-12-28 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MLReuest',
            new_name='MLRequest',
        ),
    ]
